// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQELhpxUdBTwpWQldfmDuToB-gUiC05AA',
    appId: '1:674379051032:web:2c74cdc6d01e1c3d7a936d',
    messagingSenderId: '674379051032',
    projectId: 'firestore-demo-660d1',
    authDomain: 'firestore-demo-660d1.firebaseapp.com',
    storageBucket: 'firestore-demo-660d1.appspot.com',
    measurementId: 'G-Q1L45JJHPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPGoF-nYnupG3wc99lmtaqlptUD6cUY1w',
    appId: '1:674379051032:android:a80fc2c942e4beec7a936d',
    messagingSenderId: '674379051032',
    projectId: 'firestore-demo-660d1',
    storageBucket: 'firestore-demo-660d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwM2V5M83pk150-Q69s3XsQstq_YpKvCM',
    appId: '1:674379051032:ios:ae9c2e04d93b9f847a936d',
    messagingSenderId: '674379051032',
    projectId: 'firestore-demo-660d1',
    storageBucket: 'firestore-demo-660d1.appspot.com',
    androidClientId: '674379051032-l5f7dte44t571f17ed8o3c55611loic2.apps.googleusercontent.com',
    iosClientId: '674379051032-pcmnq3htre09rpgjmhkkc56lftqjh9bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.firestoreApp',
  );
}
